name: Unit Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        environment: [test]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Ensure pixi dir exists
        run: mkdir -p .pixi
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.63.2
          environments: ${{ matrix.environment }}
          frozen: true
          cache: false

      - name: Run tests
        run: pixi run -e ${{ matrix.environment }} test
